title = "A corner of Zenith"
baseURL = 'https://xenith.xyz/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID

defaultContentLanguage = "en-us"


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Zenith"
  defaultColor = "dark" # set default color mode: dark or light
  description = "A corner at the end of the internet"

[params.author]
  avatar = "avatar.jpg"
  intro = "At my Zenith"
  name = "Zenith"
  description = "Hi, welcome to my corner of the internet. Yes `zenith.xyz` was taken, and no I am not considering any other names."

[[params.socialIcons]]
name = "github"
url = "https://github.com/dotzenith"
