title = "Danshu's Musings"
baseURL = 'https://blog.danshu.co/'
languageCode = 'en-us'
defaultContentLanguage = "en-us"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

[module]
  [[module.imports]]
    path = "github.com/dotzenith/hugo-blog-awesome"
    disable = false

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/en"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-us.params]
  sitename = "Danshu's Musings"
  defaultColor = "auto"
  description = "Musings at the end of the internet"
  mainSections = ['posts']
  images = ['images/main-og.jpg']
  toc = false
  tocOpen = false
  goToTop = true
  additionalScripts = ['js/custom.js', 'js/custom-2.js']

[Languages.en-us.params.author]
  avatar = "avatar.jpg"
  intro = "Occasionally, I think"
  name = "Danshu"
  description = "Hi, welcome to my corner of the internet. Every now and then, a thought comes to me, and this is a place for me to put them down."

[[params.socialIcons]]
name = "github"
url = "https://github.com/dotzenith"
