title = "Danshu's Musings"
baseURL = "https://blog.danshu.co/"
locale = "en-us"
disableKinds = ["taxonomy", "term"]

[module]
  [[module.imports]]
    path = "github.com/dotzenith/terminal-blog"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 20
  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 30

[params]
  description = "Musings at the end of the internet"
  defaultColor = "auto"

  [params.author]
    intro = "Occasionally, I think"
    name = "Danshu"
    description = "Hi, welcome to my corner of the internet. Every now and then, a thought comes to me, and this is a place for me to put them down."

  [params.analytics]
    umamiWebsiteID = "afe14649-c5af-44f3-860c-dec3768e6c8a"

  [params.socialImage]
    endpoint = "https://og.danshu.co/generate"
    site = "blog.danshu.co"
    defaultSize = 50
